// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLgmAb5jdvxrD-kl6eZKeB2nq6A-rpro',
    appId: '1:764966431946:web:66e978035aa9c93f9d9833',
    messagingSenderId: '764966431946',
    projectId: 'taskmateb1',
    authDomain: 'taskmateb1.firebaseapp.com',
    storageBucket: 'taskmateb1.appspot.com',
    measurementId: 'G-6CVBPV1L62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-f5eZV1TdZjBl2RGdETyXP_jKyLtDRv4',
    appId: '1:764966431946:android:c4358f81bba2246e9d9833',
    messagingSenderId: '764966431946',
    projectId: 'taskmateb1',
    storageBucket: 'taskmateb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl22uj1YBsutxTuXxt2iGu-L1ArLKOiz0',
    appId: '1:764966431946:ios:2c8467003dfac8409d9833',
    messagingSenderId: '764966431946',
    projectId: 'taskmateb1',
    storageBucket: 'taskmateb1.appspot.com',
    iosBundleId: 'com.taskmateapp.taskmate',
  );
}
