// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXAfnvMdgLnTtQqMZ22uvvy3q_iuTtL6E',
    appId: '1:399870505448:web:6f6f8c6a2d1717dfd5745d',
    messagingSenderId: '399870505448',
    projectId: 'taskmateb2',
    authDomain: 'taskmateb2.firebaseapp.com',
    storageBucket: 'taskmateb2.appspot.com',
    measurementId: 'G-7GYKKMNDC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw0YhGJYyoc6RG_Pb0h20EELyjQGtOrMo',
    appId: '1:399870505448:android:b509d1fcfbcb0783d5745d',
    messagingSenderId: '399870505448',
    projectId: 'taskmateb2',
    storageBucket: 'taskmateb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAplNcC9JSwW4I6otVCmm1iTjokllyw3Ag',
    appId: '1:399870505448:ios:a8ac8a12011f5030d5745d',
    messagingSenderId: '399870505448',
    projectId: 'taskmateb2',
    storageBucket: 'taskmateb2.appspot.com',
    iosBundleId: 'com.taskmateapp.taskmate',
  );
}
