// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqNE-4n1fGNitvkyZ9-aw-iNIdlyDTG1U',
    appId: '1:480644203885:web:29f78d79abd7fb7f478664',
    messagingSenderId: '480644203885',
    projectId: 'taskmate-4fc48',
    authDomain: 'taskmate-4fc48.firebaseapp.com',
    storageBucket: 'taskmate-4fc48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRB_sQbwHOLKASu5nltnMSyOlvrGdaGY',
    appId: '1:480644203885:android:abc3816bf4fa665d478664',
    messagingSenderId: '480644203885',
    projectId: 'taskmate-4fc48',
    storageBucket: 'taskmate-4fc48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHNcQ0XeCY-f2C3U8kHbCLVo3kaIpeX2E',
    appId: '1:480644203885:ios:d0004884c63c9f4e478664',
    messagingSenderId: '480644203885',
    projectId: 'taskmate-4fc48',
    storageBucket: 'taskmate-4fc48.appspot.com',
    iosBundleId: 'com.taskmateapp.taskmate',
  );
}
