name: TaskMate CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clones repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.TASKMATE_ANDROID_FIREBASE_APP_ID}}
#         token: ${{secrets.FIREBASE_TOKEN}}
          serviceCredentialsFileContent: ${{ secrets.TASKMATE_SERVICE_CREDENTIAL}}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk

