name: TaskMate CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.0

      - name: Install Dependencies
        run: flutter pub get

      # Uncomment if you want to run tests
      # - name: Run Tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: List APK Directory
        run: ls -la build/app/outputs/flutter-apk/

      - name: Set Timestamp
        id: set_timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Rename APK with Timestamp
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/taskmate-${{ env.TIMESTAMP }}.apk

      - name: List APK Directory after renaming
        run: ls -la build/app/outputs/flutter-apk/

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.TASKMATE_ANDROID_FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.TASKMATE_SERVICE_CREDENTIAL }}
          groups: testers
          file: build/app/outputs/flutter-apk/taskmate-${{ env.TIMESTAMP }}.apk
